### ISSUE TITLE
How customize tick class

### ISSUE THREAD

**Issue by jrichardsz** [mermaidjs/mermaid.cli#103]
I need to change the opacity. I added a style to the header but it is ignored:

```
  <style>
     .grid .tick {
      stroke:#d3d3d3;
      opacity:1;
      shape-rendering:crispEdges
     }
  </style>
```

![image](https://user-images.githubusercontent.com/3322836/141507172-f65d2d9e-5549-4fd7-ad31-3cae81493b3d.png)

Also I tried with initialize 
```
  var config = {
      themeCSS: "#mermaid .grid .tick { opacity: 1}",
    };
    mermaid.initialize(config);
```
But the opacity 0.3 don't change :(

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
