### ISSUE TITLE
Actually customize a theme

### ISSUE THREAD

**Issue by akloster** [mermaidjs/mermaid.cli#107]
I am wondering how to actually customize a theme without forking the whole package.

For one thing I am using mermaid from react, so with `startOnLoad: false` and a custom loader. And I can't override the `themeVariables` in the graph source code, nor do I want to do so in each source code. There is an FAQ entry that talks about it, but it makes zero sense to me.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

Although, I think this might be a https://github.com/mermaid-js/mermaid issue instead :)
There is some documentation about it on the website at https://mermaid.js.org/config/theming.html that might help for modern versions of mermaid.
