### ISSUE TITLE
Cannot export erDiagram

### ISSUE THREAD

**Issue by ShinJustinHolly3317** [mermaidjs/mermaid.cli#108]
I execute below command
`mmdc -i ./inuptDB.mmd -o ./outputDB.png -t neutral -H 800 -w 2400`

then got below error

```
Expecting 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', got 'ALPHA'
    at Yt.parseError (file:///Users/justinkao/.nvm/versions/node/v12.22.10/lib/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/justinkao/.nvm/versions/node/v12.22.10/lib/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses 
```

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
