### ISSUE TITLE
Cannot export mermaid script with "autonumber" tag

### ISSUE THREAD

**Issue by fhyfr** [mermaidjs/mermaid.cli#114]
I try to export my mermaid script (which there is "autonumber" tag inside the script) to PNG file then i got this error 

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Evaluation failed: Error: Parse error on line 9:
... API    autonumber    C ->> GS: Quer
---------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got 'NL'
```

but if i remove the "autonumber" tag it's successfully exported.
Is this supported by mermaid.cli? 

Thank you

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
