### ISSUE TITLE
Pipe to stdout ?

### ISSUE THREAD

**Issue by AlexMVoiture** [mermaidjs/mermaid.cli#116]
How can I take a mermaid graph from Stdin and then generate a diagram in the svg format to the STDOUT ? I've tried mermaid-cli, but I can't find a way to do it. Only stdin seems to be offered.

At the moment, I am generating graphs by loading up mermaid.min.js into a web browser and using the render function. Is it possible to do so without the web browser component ?

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

This isn't currently supported, but you're welcome to make a pull request in the `@mermaid-js/mermaid-cli` project if you are interested!

`@mermaid-js/mermaid-cli` also now has a Node.JS API, so if you're familiar with JavaScript, you can write your own Node.JS script to do this for you.
