### ISSUE TITLE
Please restore the ability to configure sequence and gantt options

### ISSUE THREAD

**Issue by kellerj** [mermaidjs/mermaid.cli#14]
Is it possible to restore the --sequenceConfig and --ganttConfig options to the CLI.  I was making use of them in the 7.0.x versions and have had to remain on pre 7.1 mermaid due to this CLI change.  Thanks.

**Comment by agusmba** [comment]
I made ageneral config attempt at https://github.com/mermaidjs/mermaid.cli/pull/11
Could you check if that would work for you?

**Comment by tylerlong** [comment]
I have merged the PR from @agusmba and released a new version.
