### ISSUE TITLE
theme option in json config is not working

### ISSUE THREAD

**Issue by agusmba** [mermaidjs/mermaid.cli#19]
Right now, if you add the `theme` configuration to the json config, it is ignored, and either `default` or the theme given in the commandline with `-t` is used.

The `theme` configuration in the json should be taken into account, as per mermaid documentation.

Note that if `-t` command line is used, it should take precedence over the json theme config

I'll add a PR shortly

**Comment by tylerlong** [comment]
Fixed. Please reopen if you can still reproduce this issue with latest version.

**Comment by tim2CF** [comment]
can reproduce it in mermaid 0.5.1, mac os

**Comment by tim2CF** [comment]
`-t` cli option works, but if theme is set in config only - option is ignored @tylerlong
