### ISSUE TITLE
Incorrect JSON config may hang mermaid.cli

### ISSUE THREAD

**Issue by agusmba** [mermaidjs/mermaid.cli#20]
If the user creates a syntactically incorrect json, mermaid.cli could hang:

```
$ node index.bundle.js -i input.mmd -o output.png -c config.json -C CSS.css -w 1500
(node:9056) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token / in JSON at position 63
(node:9056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have a fix ready for throwing a proper error and exiting if the json is incorrect.

Will PR shortly

**Comment by tylerlong** [comment]
I will close it because I think it behaves properly. If user provides invalid JSON, the app tells the user that there is `SyntaxError: Unexpected token / in JSON`.

So user could fix the invalid JSON. There isn't much that we can do.

**Comment by ismarslomic** [comment]
When using MermaidJS CLI in CI/CD pipelines, throwing error in stead of having hanging job (because CLI hangs) is crucial. Even when using CLI manually I dont see any reason for not throwing error and exiting the service
