### ISSUE TITLE
Configue puppeteer

### ISSUE THREAD

**Issue by brendo** [mermaidjs/mermaid.cli#23]
It'd be really nice if we were able to configure Puppeteer's [runtime settings](https://github.com/GoogleChrome/puppeteer#default-runtime-settings). In my use case, I'd like to install Chromium into a docker image, set [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#environment-variables) and then pass through the [`executablePath`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions) option to [`puppeteer.launch()`](https://github.com/mermaidjs/mermaid.cli/blob/master/index.js#L71).

How do you think we could do this? Happy to do the legwork :)

**Comment by mzlogin** [comment]
I met the same problem, and a manually workaround it like this (in Windows):

1. set  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
2. install mermaid.cli global
3. edit ~/AppData/Roaming/npm/node_modules/mermaid.cli/index.bundle.js
    line 63, change `puppeteer.launch()` to `puppeteer.launch({executablePath: '/path/to/chrome.exe'})`

May be that can help.

**Comment by brendo** [comment]
It's helpful, but it won't work in my scenario as the job runs in a CI
environment and with fresh NPM artifacts.

I'll likely submit an MR for this when I get a chance.
