### ISSUE TITLE
Passing an optional stylesheet does nothing on sequence diagrams

### ISSUE THREAD

**Issue by pierrebonbon** [mermaidjs/mermaid.cli#28]
As the title says, I am trying to pass an optional stylesheet for a sequence diagram but it outputs a file, svg, png or pdf without applying it. Tried several configurations on the .css file without success. Here is a simple one I tried:

    .actor {
      stroke:black;
      fill:none;
    }

    text.actor {
      fill:black;
      stroke:none;
      font-family:Arial, Helvetica, sans-serif;
    }

    .actor-line {
      stroke:black;
    }

And on the command line: 

    mmdc -i seqdiagram.mmd -o seqdiagram.png -C stylesheet.css

I do not seem to be doing anything wrong. I wonder if everyone else is unable to apply an optional stylesheet to sequence diagrams?

**Comment by pierrebonbon** [comment]
The problem seems to be on the `mermaid.cli` side, as I can change the style for all elements on mermaid's webpage using the developer tools. Here's a screenshot:

![screenshot_2](https://user-images.githubusercontent.com/11869768/36937674-dbab442c-1f0e-11e8-8b31-f69877d02b8e.jpg)

For some weird reason, with a similar diagram and stylesheet as the above, I am only able to change the font-family for `.labelText`, `.loopText`, `.messageText` and `text.actor` but not `.noteText` on the command line.

**Comment by agusmba** [comment]
This is a problem with the core library, see https://github.com/knsv/mermaid/issues/587
Following the "official" way of setting the css does not work for all the items it should.

See also https://github.com/mermaidjs/mermaid.cli/pull/24 for a PR which would also fix this, but it's on hold since it should be fixed in the core library.

**Comment by tylerlong** [comment]
Please refer to https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785
