### ISSUE TITLE
width / height options do not alter the size of the generated PNG

### ISSUE THREAD

**Issue by Lucas-C** [mermaidjs/mermaid.cli#3]
Hi.

I'm not sure if this is a bug or feature request,
but currently it is not posible to generate a bigger PNG using the `-w` / `-H` flags

**Comment by tylerlong** [comment]
widget and height are actually web page size instead of the generated image size. For example: `1-w 800 -H 600` means: generate the images in a 800*600 browser window.

The cli is just a thin wrapper around the mermaid library. I guess in a real browser, you cannot change the image size either.

You can look at the code of the CLI, fewer than 100 LoC. Please share your opinions and suggestions.

**Comment by Lucas-C** [comment]
I sent a PR that fixes the scaling
I still have a strange rendering bug, I'm going to open another issue for it

**Comment by tylerlong** [comment]
Please read the comments here: https://github.com/mermaidjs/mermaid.cli/pull/4#issuecomment-334980830

> Overall this should be a mermaid issue. Mermaid doesn't allow user to manually set a width for the charts. It figures out the width according to page width and it also doesn't always take 100% of the page width.

Feel free to create an issue for the mermaid project.

**Comment by Lucas-C** [comment]
Thanks for your investigations !

Have you considered the `flowchart.useMaxWidth` flag ? cf. https://mermaidjs.github.io/mermaidAPI.html

This may be a solution, configurable from the CLI

**Comment by agusmba** [comment]
Hi @tylerlong 

It would be nice to have a way of increasing the resolution of pngs.
A working width/height options could do the trick.
Right now mermaid pngs cannot be used in documents due to their low resolution.

@Lucas-C 's fix seems to allow for better resolution sequence and flowchart graphs, but the default gantt diagram doesn't look right either at 1000 nor 2000 width.

Thank you both!

**Comment by agusmba** [comment]
@Lucas-C I will make a PR shortly allowing mermaid configuration, so you could try `flowchart.useMaxWidth`

Unfortunately this is not available for sequence diagrams. In the meantime I was thinking about solving on the cli by inserting @Lucas-C fix only in the case of png, or looking at a different rendering option like using https://github.com/exupero/saveSvgAsPng

**Comment by agusmba** [comment]
@Lucas-C The new version should allow you to use a custom css file where you could set your `max-width` workaround.

**Comment by matthew-piziak** [comment]
This does not work on version 0.5.1. Passing a `mermaid.json` to `-c` with `{"flowchart": { "useMaxWdith": true}}` still produces an image of width 130 despite passing `-w 800`.

Custom CSS does not work for SVGs, so one can't even render to SVG and then scale up with a different program without giving up the ability to specify, e.g. custom fonts.

**Comment by matthew-piziak** [comment]
Reconfirmed the above on mmdc version `8.4.8`.

**Comment by matthew-piziak** [comment]
Okay, I figured it out.

Pass this to `--cssFile`:
```
#container > svg {
    max-width: 100% !important;
}
```
…and this to `--configFile`:
```
{
  "flowchart": {
      "useMaxWidth": true
  }
}
```

**Comment by ilyakooo0** [comment]
@matthew-piziak Could you elaborate what you meant by `--scale`? `mmdc` doesn't seem to have a `--scale` option.

**Comment by IAXES** [comment]
I just had to create the `cssFile` @matthew-piziak mentions above, then I could create my scaled output via the latest docker image (`npm` seems to be pulling an outdated version for some reason), via:

```sh
docker run -v $(pwd):/work \
    minlag/mermaid-cli:latest \
    -i "/work/mermaid.mmd" 
    --scale 4 \
    -o "/work/out.png" \
    -b transparent \
    --cssFile "/work/cssfile"
```

The only downside is that this seems to create a lot of excess horizontal border area around the image, so I just copy-paste it into something like GIMP and "crop to content". Not sure if there's a trivial way to automate this via imagemagick or some other CLI tool. Could likely (not 100% sure) achieve this via `convert input.png -flatten -fuzz 1% -trim +repage output.png`.

**Comment by connorjs** [comment]
Note: Simply using `-trim` worked for me. (Thanks for the tip!)

```sh
convert input.png -trim output.png
```
