### ISSUE TITLE
Those exported svg files can be viewed in chrome, but not in IE or Visio

### ISSUE THREAD

**Issue by toaco** [mermaidjs/mermaid.cli#30]

**Comment by tylerlong** [comment]
Please specify IE version and Visio version. And what's your operating system?

**Comment by toaco** [comment]
The latest version of IE and Visio2007 on Win10.

**Comment by toaco** [comment]
Are we using SVG2? I found a potentially useful post: https://stackoverflow.com/questions/40137663/why-is-my-svg-appearing-in-chrome-but-not-ie-or-ff

**Comment by tylerlong** [comment]
I don't have a solution at the moment. A workaround is to export PDF/PNG instead of SVG.

**Comment by kristinclemens** [comment]
I have the same experience in PowerPoint. Using PNG for now.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

FYI, this issue looks similar to https://github.com/mermaid-js/mermaid-cli/issues/447. The SVGs created by Mermaid use a few new features that only exist in modern browsers, so they're usually not compatible with older or non-browser software.
