### ISSUE TITLE
Do not validate argument filenames

### ISSUE THREAD

**Issue by benjamin-demarteau** [mermaidjs/mermaid.cli#33]
Very few CLI tools bother validating the extensions of the files providing using the command line, extensions mean nothing, it's just a convention.

A good example is generating css on the fly for a specific invocation using shell substitution:

```bash
$ mmdc -i analysis_reseller-transfer-validation.md -o analysis_reseller-transfer-validation.md.svg --cssFile <(echo 'text { font-family: monospace }')

CSS file must end with ".css"
```

**Comment by tylerlong** [comment]
Good suggestion. PR is welcome. Or I will take some time to do it in the future.

**Comment by benjamin-demarteau** [comment]
> For --cssFile <(echo 'text { font-family: monospace }') I am not sure it will work. Because in the code I just fs.readFileSync(filepath, 'utf-8').

It will, the program will get a path to `/dev/fd/<some number>` that behaves exactly like a file except that it can only be read once. It's transparent for most programs.

**Comment by benjamin-demarteau** [comment]
Done
