### ISSUE TITLE
Generated PDF width/height

### ISSUE THREAD

**Issue by YYOANN** [mermaidjs/mermaid.cli#35]
The width and height (-w / -H) options are not working when generating a pdf.

Simple test `mmdc -i in -o out.pdf -H 200`

With `in` file containing:
```mermaid
graph TD
A(test) --> B
B(test) --> C
C(test) --> D
D(test) --> E
E(test) --> F
F(test) --> G
G(test) --> H
H(test) --> I
I(test) --> J
J(test) --> K
K(test) --> L
L(test) --> M
M(test) --> N
N(test) --> O
O(test) --> P
P(test) --> Q
Q(test) --> R
R(test) --> S
S(test) --> T
T(test) --> U
U(test) --> V
V(test) --> W
W(test) --> X
X(test) --> Y
Y(test) --> Z
Z(test)
```

**Comment by YYOANN** [comment]
Solved using a CSS file `test.css` containing

```css
#container > svg {
    max-height: 20cm !important;
}
```

And using `mmdc -i in -o out.pdf -C test.css`

**Comment by tylerlong** [comment]
```
-w, --width [width]                             Width of the page. Optional. Default: 800 (default: 800)
    -H, --height [height]                           Height of the page. Optional. Default: 600 (default: 600)
```
`-w` & `-H` is for the size of the page(size of the browser window), not for the chart size.

**Comment by YYOANN** [comment]
Only if possible, it would be great to be able to set the max width/height of the generated pdf/png output without adding a custom CSS file.

The problem originated while trying to generate a pdf file from a markdown file using pandoc and "raghur/mermaid-filter". The result was a truncated graph.

**Comment by boekabart** [comment]
I think this is the most correct CSS solution for this:
```css
@media print{
  @page {
    size: landscape
  }
}
```
(tested, works like a charm)
You can also set margins, print size (A4, letter, A3) etc this way.

**Comment by CGMossa** [comment]
How can I find all the "available" options for this? This is not really a solved issue.

**Comment by databinding-thierryiseli** [comment]
@CGMossa I agree with you. I'm still trying to figure that out...
