### ISSUE TITLE
Error: Failed to launch Chrome

### ISSUE THREAD

**Issue by jaepd** [mermaidjs/mermaid.cli#37]
This happens whether I install globally or locally. I'll attach the whole log, but the first two lines seem the most important:
```
(node:6152) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!
[0504/091123.638219:FATAL:zygote_host_impl_linux.cc(124)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_developm
ent.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.  
```

I'm using Node v9.11.1, NPM v5.8.0, on a vanilla Arch Linux x64 installation. Mermaid used to work for me (like a year ago when I last used it).

[logs.log](https://github.com/mermaidjs/mermaid.cli/files/1973511/logs.log)

**Comment by tylerlong** [comment]
https://github.com/mermaidjs/mermaid.cli/pull/32#issuecomment-385145371

https://github.com/GoogleChrome/puppeteer/issues/290#issuecomment-322882177

Please upgrade to a newer kernel.

What's your kernel version by the way?

**Comment by tylerlong** [comment]
Refer to https://github.com/mermaidjs/mermaid.cli#linux-sandbox-issue

**Comment by jaepd** [comment]
Thank you! I'll try it after updating

**Comment by RidaAyed** [comment]
Hi. Same problem here. Remains after full update:  
`4.16.13-1-ARCH`
