### ISSUE TITLE
Feature: Add streaming support

### ISSUE THREAD

**Issue by sbussard** [mermaidjs/mermaid.cli#40]
It would be nice to be able to pipe data into the cli rather than have to use a file

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

As a side-note, `@mermaid-js/mermaid-cli` does current support piping data into the CLI, but it doesn't yet support piping data out of the CLI.
