### ISSUE TITLE
Mermaid for Atom Package Styling?

### ISSUE THREAD

**Issue by drosenstark** [mermaidjs/mermaid.cli#46]
Is there an easy way to get the styling used by the Mermaid for Atom Package to be used here. Both are convenient, of course.

Thanks!

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
