### ISSUE TITLE
Installing globally is good.

### ISSUE THREAD

**Issue by skyzyx** [mermaidjs/mermaid.cli#47]
Instead of asking people not to install globally, why not teach them how to do it properly? https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
