### ISSUE TITLE
When using a <code> tag, the text overflows in the PNG output

### ISSUE THREAD

**Issue by Lucas-C** [mermaidjs/mermaid.cli#5]
Source:
```text
graph TD
pc(<code>.pre-commit-config.yaml</code>)
```
Result:
![test](https://user-images.githubusercontent.com/925560/30591822-a7eabfe2-9d44-11e7-9e62-f2058d7265f1.png)

**Comment by tylerlong** [comment]
Seems to be OK in live editor: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z3JhcGggVEQKcGMoPGNvZGU-LnByZS1jb21taXQtY29uZmlnLnlhbWw8L2NvZGU-KQo

More investigation needed.

**Comment by tylerlong** [comment]
It is caused by font. `<code>` had different font from the other part of the page.

I added `index.css` to fix the issue. https://github.com/mermaidjs/mermaid.cli/commit/bbb178cabee4887bf8b23f50976969da1e1ce095

**Comment by Lucas-C** [comment]
Thank you very much !
