### ISSUE TITLE
Is there any way to set dpi for png

### ISSUE THREAD

**Issue by shixuguo** [mermaidjs/mermaid.cli#51]
in some condition , I have to use png instead of svg
but the default dpi for png is too low (=72)
Is there any way to set dpi for png

**Comment by cherrot** [comment]
I also need this feature. Is there any updates? thanks.

**Comment by IAXES** [comment]
Please see https://github.com/mermaidjs/mermaid.cli/issues/3

There are various solutions there to rapidly achieve this. Should be able to close this issue.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

There is a `--scale` argument, so you could set `--scale 2` to double to DPI, and see if that helps!
