### ISSUE TITLE
Custom stylesheet not being used when generating SVGs

### ISSUE THREAD

**Issue by trueskawka** [mermaidjs/mermaid.cli#54]
The custom styles from a stylesheet seem to not be properly appended when generating an SVG.

I think the issue has to do with the output type logic, mainly:
```
  if (output.endsWith('svg')) {
    const svg = yield page.$eval('#container', function (container) {
      return container.innerHTML;
    });
    fs.writeFileSync(output, svg);
  }
```

The `container.innerHTML` only has styles that come from Mermaid, as the custom stylesheet is being appended to the `head` of the HTML document.

I think the workaround would be to append the styles to the `style` element of the SVG container, I was able to monkey patch it in my project with:

1. moving `style` to the outer scope of `if (myCSS)` block

2. adding the style in for SVG
```
  if (output.endsWith('svg')) {
    const svg = yield page.$eval('#container', function (container) {
      if (style) {
        const styles = container.getElementsByTagName('style')[0];
        styles.innerHTML += style.innerHTML;
      }
      return container.innerHTML;
    });
    fs.writeFileSync(output, svg);
  }
``` 

Not sure if that's the direction you want to go with - I can create a PR if it seems reasonable.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

I believe the current version of `@mermaid-js/mermaid-cli` is doing something similar, see https://github.com/mermaid-js/mermaid-cli/blob/57f826263e52c7ff821372c1c3f3a811c36ff7bf/src/index.js#L266-L272 and https://github.com/mermaid-js/mermaid-cli/pull/358
