### ISSUE TITLE
svg generated file is not scrollable

### ISSUE THREAD

**Issue by SudeepK20** [mermaidjs/mermaid.cli#55]
I am generating svg file from cli for my sequence diagram and its not scrollable. I am using default config json file while running cli. Any idea how to make svg scrollable using custom css in config file or using any other property in config file?

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
