### ISSUE TITLE
Parsing subgraph fails on brackets

### ISSUE THREAD

**Issue by CGMossa** [mermaidjs/mermaid.cli#68]
Using `subgraph node_title[Better title]` works in the mermaid editor based on `8.40`.
It does not work on `mmdc`.

### Example

```
$ mmdc -i dummy.mmd -o dummy.svg
(node:1616) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 2:
...raph TBsubgraph BIG[better]A-->Bend
----------------------^
Expecting 'SEMI', 'NEWLINE', 'SPACE', 'EOF', 'GRAPH', 'DIR', 'TAGEND', 'TAGSTART', 'UP', 'DOWN', 'subgraph', 'end', 'SQE', 'PE', '-)', 'DIAMOND_STOP', 'MINUS', '--', 'ARROW_POINT', 'ARROW_CIRCLE', 'ARROW_CROSS', 'ARROW_OPEN', 'DOTTED_ARROW_POINT', 'DOTTED_ARROW_CIRCLE', 'DOTTED_ARROW_CROSS', 'DOTTED_ARROW_OPEN', '==', 'THICK_ARROW_POINT', 'THICK_ARROW_CIRCLE', 'THICK_ARROW_CROSS', 'THICK_ARROW_OPEN', 'PIPE', 'STYLE', 'LINKSTYLE', 'CLASSDEF', 'CLASS', 'CLICK', 'DEFAULT', 'NUM', 'PCT', 'COMMA', 'ALPHA', 'COLON', 'BRKT', 'DOT', 'PUNCTUATION', 'UNICODE_TEXT', 'PLUS', 'EQUALS', 'MULT', got 'SQS'
    at Yt.parseError (file:///C:/Users/[CENSORED]/AppData/Local/Yarn/Data/global/node_modules/mermaid.cli/mermaid.min.js:1:486512)
[...]
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:1616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
where `dummy.mmd` contains: 

```mermaid
graph TB
subgraph BIG[better]
A-->B
end
```

For example see [mermaid live editor with this example](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiXG5ncmFwaCBUQlxuc3ViZ3JhcGggQklHW2JldHRlcl1cbkEtLT5CXG5lbmQiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ). 

Finally,

```
$ mmdc -V
0.5.1
```

**Comment by zerok** [comment]
I had a similar issue with hexagonal nodes. The issue seems to be, that mermaid.cli ships with an old version of mermaid.min.js which doesn't support these kinds of node types/attributes. I've solved this by also explicitly installing mermaid and then copying dist/mermaid.min.js into the mermaid.cli folder within node_modules :)

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
