### ISSUE TITLE
Allow a markdown file as input

### ISSUE THREAD

**Issue by johnbillion** [mermaidjs/mermaid.cli#7]
I'd love to be able to specify a markdown file as input and have `mmdc` generate its output based on mermaid code blocks within the file.

Example input markdown file:

~~~markdown readme.md
# My Project

My project provides this service:

```mermaid
graph TB
    A(Input) --> B[Processing]
    B --> C(Output)
```

And this service:

```mermaid
graph TB
    A(Blue) --> B[Yellow]
    B --> C(Green)
```
~~~

It would be great if running the following command generated two PNG files, one for each mermaid code block found in the file.

    mmdc -i readme.md -o output.png

The files could be sequentially named `output-1.png` and `output-2.png`, or it could be made a requirement to specify a placeholder in the filename for numeric replacement, eg:

    mmdc -i readme.md -o output-%s.png

Thoughts?

**Comment by tylerlong** [comment]
It's a great idea. However it's out of the scope of this project. mermaid is not a markdown parser.

**Comment by raghur** [comment]
I wrote one sometime ago - see https://github.com/raghur/mermaid-filter
