### ISSUE TITLE
mmdc process does not exit on error

### ISSUE THREAD

**Issue by pepijnve** [mermaidjs/mermaid.cli#77]
Running `mmdc` with an input file that contains syntax errors will result in the process hanging indefinitely.
```
mmdc -o test.svg -i test.mmd 
(node:18311) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 1:
S[Start Mobile Appli
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:486512)
...
    at /Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Running `node` with `--unhandled-rejections=strict` fixes this. The default behaviour makes usage of `mmdc` in a non-interactive context rather problematic.

**Comment by pepijnve** [comment]
This was solved by https://github.com/mermaid-js/mermaid-cli/pull/19 in more recent versions of the mermaid CLI.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

I can confirm that `@mermaid-js/mermaid-cli` does exit if `mermaid` throws an error!
