### ISSUE TITLE
How to have a double sided arrow?

### ISSUE THREAD

**Issue by Boris-Scharinger** [mermaidjs/mermaid.cli#78]
Tried <--> in a flow chart but it won't do. Did I overread something or is this not possible?

**Comment by fengsaofly** [comment]
Me too! How to solve it ? @tylerlong

**Comment by fengsaofly** [comment]
Me too! How to solve it ? @tylerlong

**Comment by JulioSDDR** [comment]
I also expected this behavior

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo.

[Multi-directional arrows](https://mermaid.js.org/syntax/flowchart.html#multi-directional-arrows) should be supported in the latest `@mermaid-js/mermaid-cli`. If it isn't, please feel free to open an issue in the new repo.

The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
