### ISSUE TITLE
Sub graph formatting?

### ISSUE THREAD

**Issue by Boris-Scharinger** [mermaidjs/mermaid.cli#79]
How to change the fill and stroke color and width of a subgraph box?
Thanks!

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

As a side-note, if this is a general `mermaid` question (and not related to the command-line tool), you might have better luck asking on the https://github.com/mermaid-js/mermaid repo!
