### ISSUE TITLE
Idea: export to xml (mxGraphModel)

### ISSUE THREAD

**Issue by pedrocarmona** [mermaidjs/mermaid.cli#80]
Problem:
---

- Developers prefer mermaid, business people draw.io.
- github doesnt have mermaid support yet
- Live editor is not perfect: 
  + people need context to start writing mermaid language.
  + not having ability to save / track changes.
- draw.io doesnt import/export mermaid

Playground solution
---

draw.io uses mxGraphModel.
Ability to export mermaid to mxGraphModel, would allow users to change the diagram using draw.io and then devs could write it back in mermaid.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
