### ISSUE TITLE
Pie Chart not supported?

### ISSUE THREAD

**Issue by apertureless** [mermaidjs/mermaid.cli#81]
According to the docs there are pie charts: https://mermaid-js.github.io/mermaid/#/pie

Example taken from docs page:

```
➜ cat pie.mmd     
pie
    title Key elements in Product X
    "Calcium" : 42.96
    "Potassium" : 50.05
    "Magnesium" : 10.01
    "Iron" :  5
```

**Error**

```
$MERMAID_BIN -i pie.mmd -o pie.pdf
(node:66053) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 1:
pie    title Key el
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
```

Works tho for gantt, graph, classdiagram.

**Comment by tddschn** [comment]
Same error. mmdc version: 8.5.1.

**Comment by jeff1985** [comment]
The current version of mermaid used in this repo is 8.0:
https://github.com/mermaidjs/mermaid.cli/blob/master/package.json

So I assume, that pie chart is simply not yet in v8.0

Also I see that the last update was 2 years ago:
https://www.npmjs.com/package/mermaid.cli

This repo links to the new development under https://github.com/mermaid-js/mermaid.cli/
I switched to the new repo:
```
yarn global add --production puppeteer@1.19.0 @mermaid-js/mermaid-cli
```

 and now pie charts work just fine.

**Comment by Yash-Singh1** [comment]
Take a look at #80, installed `mermaid.cli`, install `mermaid-cli`

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package and get pie charts working.
