### ISSUE TITLE
Having issues with building .mmd with rect

### ISSUE THREAD

**Issue by LouisMaycol** [mermaidjs/mermaid.cli#84]
Building the mmd file to any format throws an error:
`(node:38993) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 33:
...on form  rect rgb(0, 0, 255)  BRW-->>A
----------------------^
Expecting 'SOLID_OPEN_ARROW', 'DOTTED_OPEN_ARROW', 'SOLID_ARROW', 'DOTTED_ARROW', 'SOLID_CROSS', 'DOTTED_CROSS', got ','`

Here's the snippet of the code:

> rect rgba(0, 0, 255, 0.3)
>     Note over BRW,BRN: Mobile app syncing
>     ABA->>ABA: Record loan application locally
>     alt with internet
>       ABA->>CH: Upload loan applications
>     else without internet
>       ABA->>ABA: Generate loan applications flat file
>       ABA->>CH: Upload loan applications flat file
>     end
>     CH->>CH: Validate loan applications
>     CH->>CH: Save/update loan applications
>     CH->>ABA: Return upload status
>     ABA->>ABA: Update loan applications local copy
>     CH->>LE: Submit loan applications
>     LE->>LE: Process loan applications
>     LE->>PL: Submit processed loan applications
>   end

When I removed the rect code, it builds successfully.

I am using `"mermaid.cli": "^0.5.1"` version.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
