### ISSUE TITLE
Gantt can't set date if DateFormat set

### ISSUE THREAD

**Issue by niktob560** [mermaidjs/mermaid.cli#87]
Minimal config:
```mermaid
gantt
    dateFormat :YYYY-MM-DD
    section Electro
    AAA :crit, A, 2020-06-15, 5d                                                      
    section Supporting
    Roadmap :crit, active, rmap, 2020-04-23, 1d
```
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ2FudHRcbiAgICBkYXRlRm9ybWF0IDpZWVlZLU1NLUREXG5cbiAgICBzZWN0aW9uIEVsZWN0cm9cbiAgICBBQUEgOmNyaXQsIEEsIDIwMjAtMDYtMTUsIDVkICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgXG4gICAgc2VjdGlvbiBTdXBwb3J0aW5nXG4gICAgUm9hZG1hcCA6Y3JpdCwgYWN0aXZlLCBybWFwLCAyMDIwLTA0LTIzLCAxZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcbiAgICBkYXRlRm9ybWF0IDpZWVlZLU1NLUREXG5cbiAgICBzZWN0aW9uIEVsZWN0cm9cbiAgICBBQUEgOmNyaXQsIEEsIDIwMjAtMDYtMTUsIDVkICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgXG4gICAgc2VjdGlvbiBTdXBwb3J0aW5nXG4gICAgUm9hZG1hcCA6Y3JpdCwgYWN0aXZlLCBybWFwLCAyMDIwLTA0LTIzLCAxZFxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0)

And without dateFormat:
[![](https://mermaid.ink/img/eyJjb2RlIjoiZ2FudHRcblxuICAgIHNlY3Rpb24gRWxlY3Ryb1xuICAgIEFBQSA6Y3JpdCwgQSwgMjAyMC0wNi0xNSwgNWQgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBcbiAgICBzZWN0aW9uIFN1cHBvcnRpbmdcbiAgICBSb2FkbWFwIDpjcml0LCBhY3RpdmUsIHJtYXAsIDIwMjAtMDQtMjMsIDFkXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ2FudHRcblxuICAgIHNlY3Rpb24gRWxlY3Ryb1xuICAgIEFBQSA6Y3JpdCwgQSwgMjAyMC0wNi0xNSwgNWQgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBcbiAgICBzZWN0aW9uIFN1cHBvcnRpbmdcbiAgICBSb2FkbWFwIDpjcml0LCBhY3RpdmUsIHJtYXAsIDIwMjAtMDQtMjMsIDFkXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

Works in mermaid-cli and in the live editor

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
