### ISSUE TITLE
No arrowheads showing under v8.4.8, svg has bad marker-end url

### ISSUE THREAD

**Issue by EyePulp** [mermaidjs/mermaid.cli#88]
Howdy;
Hopefully this is simple and dumb mistake I'm making, but nothing I render has arrowheads on it.
- Version: 8.4.8
- Node: tried both v10 & v12
- Os:  MacOs Catalina

### What I've tried:
test.mmd:
```mermaid
graph LR

  foo -- yo! --> bar
```
cmd:
```bash
./node_modules/.bin/mmdc -i render/test.mmd -o render/test.svg
```
renders:
<img width="170" alt="image" src="https://user-images.githubusercontent.com/231081/82007859-e868cb80-9630-11ea-82e2-7b9cedfe646a.png">

If I run the same map in the [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcblxuICBmb28gLS0geW8hIC0tPiBiYXJcblxuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZX0):
![image](https://user-images.githubusercontent.com/231081/82009056-ebb18680-9633-11ea-9371-578a47633a8c.png)

### What I've figured out:
Looking at the `test.svg` output I do see one reference to an absolute filepath in a `marker-end` attribute, which I'm not sure about:
**marker-end="url(file:///Users/me/Projects/work/themap/node_modules/@mermaid-js/mermaid-cli/index.html#arrowhead8)"**
```svg
<g class="edgePaths">
	<g class="edgePath" style="opacity: 1;">
		<path class="path" d="M51.09375,27.5L87.2734375,27.5L123.453125,27.5" marker-end="url(file:///Users/me/Projects/work/themap/node_modules/@mermaid-js/mermaid-cli/index.html#arrowhead8)" style="fill:none">
		</path>
		<defs>
			<marker id="arrowhead8" viewBox="0 0 10 10" refX="9" refY="5" markerUnits="strokeWidth" markerWidth="8" markerHeight="6" orient="auto">
				<path d="M 0 0 L 10 5 L 0 10 z" class="arrowheadPath" style="stroke-width: 1; stroke-dasharray: 1, 0;">
				</path>
			</marker>
		</defs>
	</g>
</g>
```

It looks like if I manually edit the svg and remove the filepath and just leave **marker-end="#arrowhead8"** everything works, and I get arrows.

What am I doing wrong?

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
