### ISSUE TITLE
Allow for mermaid configuration

### ISSUE THREAD

**Issue by agusmba** [mermaidjs/mermaid.cli#9]
I'm sorry if this is already possible, I didn't see a way of specifying mermaid's configuration as explained in [Mermaid API](https://mermaidjs.github.io/mermaidAPI.html) and [Mermaid Usage](https://mermaidjs.github.io/usage.html) when using `mermaid.cli`

If it's not currently possible, would it make sense to add this feature to the cli?

It would make life easier for all users of `mermaid.cli`

Thanks!

**Comment by tylerlong** [comment]
Merged. Thank you for your PR.
