### ISSUE TITLE
Open an existing diagram in live editor

### ISSUE THREAD

**Issue by starting** [mermaidjs/mermaid.cli#92]
This is a great tool and especially the diagrams are very clean and neat and cli helps me to regenerate diagrams with a breeze. 

**Feature Request**
It would be great if I can open my existing documents in the live editor for modifications.  This will help me to reduce one step of copying and pasting. 

**Design and implementation details** 
I would like to contributes to this if I can get more details such as how the live editor initializes with its content.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.

If this is related to the mermaid-live-editor, you may want to instead make an issue in https://github.com/mermaid-js/mermaid-live-editor if this feature is still missing in the latest version of the live editor.
