### ISSUE TITLE
Custom css not working

### ISSUE THREAD

**Issue by fulljackz** [mermaidjs/mermaid.cli#94]
Hi,

I already check this comment : https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785 
But it does not seems to work on my side.

What should I do to be able to customize my diagrams links color for example ?

Regards,

**Comment by StevonixDev** [comment]
Hi,
I am also having the same Problem.

regards

**Comment by fulljackz** [comment]
Hi @StevonixDev I get it working with : 

```
{
    "theme": "forest",
    "themeCSS": "",
    "cloneCssStyles": false,
    "sequence": {
        "mirrorActors": false,
        "useMaxWidth": false
    }
}
``` in .mermaid-config.json

Then, with `~/node_modules/.bin/mmdc -o test.png -i input -c .mermaid-config.json` , it generates a diagram with my custom css.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
