### ISSUE TITLE
Support verbatim multiline text in node labels

### ISSUE THREAD

**Issue by cdmihai** [mermaidjs/mermaid.cli#99]
As far as I can tell the only way to have multiple lines of text in a node is by adding `<br>` tags:
```
graph TD
    B[Line 1<br>Line 2]
```

However, this gets really tedious for larger text, and I'd really like if we could do this:
```
graph TD
    B[
        Line 1
        Line 2
        ...
        Line n
     ]
```

**Comment by forrestbao** [comment]
I also wish this can be available. It allows me to add code into charts.

**Comment by aloisklink** [comment]
Development has moved to the https://github.com/mermaid-js/mermaid-cli repo, please re-open your issue there if it's still relevant.
The package has also been renamed on NPM to [`@mermaid-js/mermaid-cli`](https://www.npmjs.com/package/@mermaid-js/mermaid-cli), so you may need to run `npm uninstall mermaid.cli && npm install @mermaid-js/mermaid-cli` to get the latest version of this package.
